# Generated by Django 6.0.3 on 2026-04-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("tournament_name", models.CharField(blank=True, max_length=200)),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("match_date", models.DateField(blank=True, null=True)),
                ("toss_decision", models.CharField(blank=True, max_length=20)),
                ("status", models.CharField(default="live", max_length=30)),
                ("stream_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("jersey_number", models.PositiveIntegerField(blank=True, null=True)),
                ("batting_hand", models.CharField(blank=True, max_length=20)),
                ("bowling_style", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["team__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Innings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("innings_number", models.PositiveSmallIntegerField()),
                ("total_overs_limit", models.PositiveSmallIntegerField(default=20)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innings",
                        to="matches.match",
                    ),
                ),
                (
                    "batting_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batting_innings",
                        to="matches.team",
                    ),
                ),
                (
                    "bowling_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bowling_innings",
                        to="matches.team",
                    ),
                ),
            ],
            options={
                "ordering": ["innings_number"],
                "unique_together": {("match", "innings_number")},
            },
        ),
        migrations.CreateModel(
            name="BallEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("over_number", models.PositiveSmallIntegerField()),
                (
                    "ball_number",
                    models.PositiveSmallIntegerField(
                        help_text="Use 1-6 for legal ball slot in the over."
                    ),
                ),
                ("runs_off_bat", models.PositiveSmallIntegerField(default=0)),
                ("extras", models.PositiveSmallIntegerField(default=0)),
                (
                    "extra_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("wide", "Wide"),
                            ("no_ball", "No Ball"),
                            ("bye", "Bye"),
                            ("leg_bye", "Leg Bye"),
                            ("penalty", "Penalty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_legal_delivery", models.BooleanField(default=True)),
                ("wicket_fell", models.BooleanField(default=False)),
                (
                    "wicket_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("bowled", "Bowled"),
                            ("caught", "Caught"),
                            ("lbw", "LBW"),
                            ("run_out", "Run Out"),
                            ("stumped", "Stumped"),
                            ("hit_wicket", "Hit Wicket"),
                            ("retired_out", "Retired Out"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fielder_name", models.CharField(blank=True, max_length=120)),
                (
                    "shot_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Unknown"),
                            ("defence", "Defence"),
                            ("drive", "Drive"),
                            ("cut", "Cut"),
                            ("pull", "Pull"),
                            ("sweep", "Sweep"),
                            ("glance", "Glance"),
                            ("lofted", "Lofted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("shot_zone", models.CharField(blank=True, max_length=50)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ball_events",
                        to="matches.innings",
                    ),
                ),
                (
                    "bowler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls_bowled",
                        to="matches.player",
                    ),
                ),
                (
                    "dismissed_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dismissals",
                        to="matches.player",
                    ),
                ),
                (
                    "non_striker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls_faced_as_non_striker",
                        to="matches.player",
                    ),
                ),
                (
                    "striker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls_faced_as_striker",
                        to="matches.player",
                    ),
                ),
            ],
            options={
                "ordering": ["over_number", "ball_number", "id"],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="matches.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_matches",
                to="matches.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_matches",
                to="matches.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="toss_winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="toss_wins",
                to="matches.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("team", "name")},
        ),
    ]
