# Generated by Django 6.0.3 on 2026-04-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballevent",
            name="shot_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("defence", "Defence"),
                    ("leave", "Leave"),
                    ("drive", "Drive"),
                    ("cover_drive", "Cover Drive"),
                    ("straight_drive", "Straight Drive"),
                    ("on_drive", "On Drive"),
                    ("lofted_drive", "Lofted Drive"),
                    ("cut", "Cut"),
                    ("late_cut", "Late Cut"),
                    ("square_cut", "Square Cut"),
                    ("pull", "Pull"),
                    ("hook", "Hook"),
                    ("sweep", "Sweep"),
                    ("reverse_sweep", "Reverse Sweep"),
                    ("paddle_sweep", "Paddle Sweep"),
                    ("glance", "Glance"),
                    ("flick", "Flick"),
                    ("clip", "Clip"),
                    ("lofted", "Lofted Shot"),
                    ("slog", "Slog"),
                    ("switch_hit", "Switch Hit"),
                    ("ramp", "Ramp"),
                    ("upper_cut", "Upper Cut"),
                    ("scoop", "Scoop"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ballevent",
            name="shot_zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("straight", "Straight"),
                    ("long_off", "Long Off"),
                    ("deep_extra_cover", "Deep Extra Cover"),
                    ("cover", "Cover"),
                    ("point", "Point"),
                    ("third_man", "Third Man"),
                    ("fine_leg", "Fine Leg"),
                    ("square_leg", "Square Leg"),
                    ("deep_mid_wicket", "Deep Mid Wicket"),
                    ("long_on", "Long On"),
                ],
                max_length=50,
            ),
        ),
    ]
