# Generated by Django 6.0.3 on 2026-04-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_alter_ballevent_shot_type_alter_ballevent_shot_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballevent",
            name="shot_zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("long_off", "Long Off"),
                    ("deep_cover", "Deep Cover"),
                    ("third_point", "Third Point"),
                    ("fine_leg", "Fine Leg"),
                    ("long_on", "Long On"),
                    ("deep_square_leg", "Deep Square Leg"),
                    ("mid_on_area", "Mid On Area"),
                    ("deep_extra_cover", "Deep Extra Cover"),
                    ("straight_inside", "Straight (Inside)"),
                    ("mid_off", "Mid Off"),
                    ("cover_inside", "Cover (Inside)"),
                    ("point_inside", "Point (Inside)"),
                    ("fine_leg_inside", "Fine Leg (Inside)"),
                    ("square_leg_inside", "Square Leg (Inside)"),
                    ("mid_on_inside", "Mid On (Inside)"),
                    ("cover_point_inside", "Cover Point (Inside)"),
                    ("short_leg", "Short Leg"),
                    ("silly_point", "Silly Point"),
                    ("silly_mid_on", "Silly Mid On"),
                    ("silly_mid_wicket", "Silly Mid Wicket"),
                ],
                max_length=50,
            ),
        ),
    ]
