# Generated by Django 6.0.3 on 2026-04-26 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_alter_ballevent_shot_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveInfographicCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("batting_dashboard", "Batting Dashboard"),
                            ("consistency_index", "Batting Consistency Index"),
                            ("pressure_performance", "Pressure Performance Index"),
                            ("shot_risk_efficiency", "Shot Risk Efficiency"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "display_area",
                    models.CharField(
                        choices=[
                            ("between_balls", "Between Balls"),
                            ("between_overs", "Between Overs"),
                            ("main_overlay", "Main Overlay"),
                            ("bottom_bar", "Bottom Bar"),
                        ],
                        default="between_balls",
                        max_length=30,
                    ),
                ),
                ("payload_sent", models.JSONField(blank=True, default=dict)),
                ("api_response", models.JSONField(blank=True, default=dict)),
                ("card_data", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_infographic_cards",
                        to="matches.innings",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_infographic_cards",
                        to="matches.player",
                    ),
                ),
            ],
        ),
    ]
