# Generated by Django 6.0.3 on 2026-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0004_liveinfographiccard"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveinfographiccard",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
